GH-83: Callout Component
TACC/Core-CMS pull request #324
Opened 2021-08-23 21:04 UTC by tacc-wbomar

# Overview / Issues

Implement
- #83 

# Changes

- Create plugin for UI component.

# Screenshots

<details>
<summary>(To Do) Form</summary>

| Plugin | Image |
| --- | --- |
| Callout | … |
| > Image | … |
| > Link | … |

</details>

<details>
<summary>(To Do) Render</summary>

…

</details>

<details>
<summary>(To Do) Structure</summary>

…

</details>

# Testing

<details>
<summary>To Do</summary>

1. Deploy GH-88 to Frontera & Core.
2. Create (minimal) [Frontera System page] (sans "Running Now" section)
3. Update the notices below to point to the appropriate builds:

> Last recorded deploy to [Frontera (dev)](https://dev.fronteraweb.tacc.utexas.edu/) was [Build #392 (Aug 9, 2021 1:02:37 PM)](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/392/).

> Last recorded deploy to [Core (dev)](https://dev.cep.tacc.utexas.edu/) was [Build #393 (Aug 9, 2021 1:04:25 PM)](https://jenkins01.tacc.utexas.edu/job/Core_Portal_Deploy/393/).

</details>

1. If no environment, then [prepare to test CMS changes](https://github.com/TACC/Core-CMS/wiki/Test-CMS-Changes).
2. In CMS container, run `python3 manage.py migrate`.
3. On CMS website, logged in as admin, add "TACC Site" > "Callout" plugin.
5. Ensure the following:
    1. title and description are optional
    2. title and description appear if provided
    3. image instructions are accurate
    4. styles match those of the callout at the bottom of the [Frontera System page]
    5. tall image remains tall\*

> \* Shrinking tall image height is tackled in 

[Frontera System page]: https://xd.adobe.com/view/90e6b252-0293-4243-7748-11d94a0763d0-e6d7/screen/ff0348ff-577d-450a-bef0-5326f3f7c705/specs/

2021-08-24 18:27 UTC, tacc-wbomar reviewed
Added notes for reviewers.

2021-09-09 19:03 UTC, duckonomy requested changes
I was able to add the plugin and overall it made sense!

However, I wasn't able to get the image to load properly and test the options yet.
I have written more details in the comments.

2021-09-09 19:03 UTC, duckonomy commented on taccsite_cms/contrib/helpers.py
> +
```suggestion
# Get list of indicies of items that start with text
# SEE: https://stackoverflow.com/a/67393343/11817077
def get_indices_that_start_with(text, list):
    """
    Get a list of indices of list elements that starts with given text
    :rtype: list
    """
    return [i for i in range(len(list)) if list[i].startswith(text)]
```
Needed to run

2021-09-13 16:04 UTC, duckonomy commented on taccsite_cms/static/site_cms/js/modules/elementTransformer.js
> +    this.content = container.querySelector(':scope > *');
This was my fault 🤦🏼. I was able to get everything working after I wiped everything.

2021-09-29 17:18 UTC, tacc-wbomar commented on taccsite_cms/contrib/helpers.py
> +            raise err
I commit the fix via 47347fa (instead of via suggestion, because I also removed a comment that referenced the `pass` usage).

2021-09-29 17:18 UTC, tacc-wbomar commented on taccsite_cms/contrib/helpers.py
> +            raise err
Also, thank you.

2021-09-29 17:19 UTC, tacc-wbomar commented on taccsite_cms/contrib/_docs/how-to-override-validation-error-from-parent-model.md
> +                raise err
I committed the fix via 47347fa (instead of via suggestion, because I also removed the comment above that referenced the `pass` usage). Thank you.

2021-09-29 17:20 UTC, tacc-wbomar commented
@duckonomy Two changes:
- d471a67
- 47347fa

2021-09-30 15:25 UTC, duckonomy approved these changes
LGTM!

2021-09-30 17:16 UTC, merged