FP-1524: Section Pattern: Simpler Fake Background
TACC/Core-CMS pull request #446
Opened 2022-02-23 22:09 UTC by tacc-wbomar

## Overview

Fix UI bugs introduced in Section pattern since their new code in #433.

## Changes

Use `box-shadow`, not `::before` to extend section backgrounds.

<details>
<summary>Minor (Related)</summary>

- Remove all the `::before` solution fodder.
- Add minimal variables to reduce verbosity.
- Note [FP-1470](https://jira.tacc.utexas.edu/browse/FP-1470) tasks.

</details>

## Screenshots

| | Before | After |
| - | - | - |
| Frontera Home | ![FP-1524 Frontera Home Before](https://user-images.githubusercontent.com/62723358/155414880-4cf9a5d4-2b20-4b64-b579-b912d6917689.png) | ![FP-1524 Frontera Home After](https://user-images.githubusercontent.com/62723358/155414875-0f6fb9a8-41f8-4adf-9c74-33bc60a73029.png) |
| Section Pattern | ![FP-1524 Section Pattern Before](https://user-images.githubusercontent.com/62723358/155414883-ec2a74be-1999-4a40-9c5d-e6fd683c0719.png) | ![FP-1524 Section Pattern After](https://user-images.githubusercontent.com/62723358/155414885-664a7159-782c-46d7-95d7-6201bd654415.png) |

## Testing

### Section Pattern

#### Local

1. Review [Core Section Pattern (dev)](https://dev.cep.tacc.utexas.edu/design-system/ui-patterns/o-section/).
    - _If you want to test locally, then replicate section pattern test page just by creating two snippets (see below steps)._
2. Confirm that two successive sections of same color have a border between them.
3. Confirm that all sections (except nested ones) have a background that extends to edge of page.
4. Confirm no other UI change compared to [FP-1524 Section Pattern Before](https://user-images.githubusercontent.com/62723358/155414883-ec2a74be-1999-4a40-9c5d-e6fd683c0719.png).

<details><summary>Snippets to Create</summary>

> __NAME: `UI: O-Section: Light`__
> HTML: `o-section--style-light`
> TEMPLATE: `snippets/manual-pattern-library/o-section.html`

> __NAME: `UI: O-Section: Dark`__
> HTML: `o-section--style-dark`
> TEMPLATE: `snippets/manual-pattern-library/o-section.html`

</details>

#### Frontera Homepage

1. Review [Frontera Homepage (pprd)](http://pprd.frontera-portal.tacc.utexas.edu/).
2. Confirm that two successive sections of same color have a border between them.
3. Confirm that all sections (except nested ones) have a background that extends to edge of page.
4. Confirm no other UI change compared to https://dev.cep.tacc.utexas.edu/design-system/ui-patterns/o-section/.

2022-02-23 22:19 UTC, tacc-wbomar reviewed
I explain code changes.

2022-02-23 22:19 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
> +  --border-width--neg: calc(-1 * var(--border-width));
**Notice.** Just a couple variables for short-term convenience. _FP-1470 (later) will bring more._

2022-02-23 22:19 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
>  }
**Explanation.**
For __dark__ sections:
- Extend existing background using a `box-shadow`, not a `::before` (which had more styles later in file).
- Move the `border-top` up from below, and use variables.

2022-02-23 22:19 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
>  }
**Explanation.**
For __light__ sections:
- Extend existing background using a `box-shadow`, not a `::before` (which had more styles later in file).
- Move the `border-top` up from below, and use variables.

2022-02-23 22:19 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
> +.o-section .o-section { box-shadow: none; }
**Explanation.**
For light __and__ dark sections:
- Delete all the cumbersome `::before` solution.
- Unset `box-shadow` (i.e. extended background) for nested sections.

2022-02-23 22:19 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
> +[class*="o-section--style"] { position: relative; }
**Explanation.** This hack was relying on `position: relative` from code above (deleted). _Now `position: relative` can exist here, cuz this is the only code that needs it._

2022-02-23 22:19 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
> +/* HACK: To hide `.o-section__banner-image` overflow */
**Explanation.** The `overflow-x: hidden` (below) is still a hack/trick, but the extended background does not benefit from it now (only the banner image does).

2022-02-23 23:25 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
> +  --border-width--neg: calc(-1 * var(--border-width));
Variables were removed. I hide my comment.

2022-02-23 23:26 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
>  }
Outdated since recent commit. Resolving comment.

2022-02-23 23:26 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
>  }
Outdated since recent comment. Resolving comment.

2022-02-23 23:27 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
>  }
**Explanation.**
For __dark__ sections:
- Extend existing background using a `box-shadow`, not a `::before` (which had more styles later in file).
- Move the `border-top` up from below, and use variables.

2022-02-23 23:27 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
>  }
**Explanation.**
For __light__ sections:
- Extend existing background using a `box-shadow`, not a `::before` (which had more styles later in file).
- Move the `border-top` up from below, and use variables.

2022-02-23 23:27 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
> +.o-section .o-section { box-shadow: none; }
Outdated since recent commit. Resolving comment.

2022-02-23 23:29 UTC, tacc-wbomar commented on taccsite_cms/static/site_cms/css/src/_imports/objects/o-section.css
> +.o-section .o-section { box-shadow: none; }
**Explanation.**
For light __and__ dark sections:
- Delete all the cumbersome `::before` solution (above this also).
- Unset `box-shadow` (i.e. extended background) for nested sections.

2022-02-28 17:59 UTC, edmondsgarrett requested changes
The border between the two sections following the banner on pprd Frontera still extends to both ends of the page. 
<img width="721" alt="image" src="https://user-images.githubusercontent.com/43251554/156034085-34f728c5-6a16-4abc-8431-afc4702872a3.png">

2022-02-28 22:12 UTC, tacc-wbomar commented
> The border between the two sections following the banner on pprd Frontera still extends to both ends of the page.
> — @edmondsgarrett 

__Yes, it does.__ Hm, maybe I deployed some other branch to Frontera pprd. _Sigh… static servers._

2022-02-28 22:34 UTC, tacc-wbomar commented
@edmondsgarrett, [Frontera pprd](https://pprd.frontera-portal.tacc.utexas.edu/) now has correct code deployed:
- this branch
- at commit up-to-date with `main`

<details>
<summary>What Happened?</summary>

I had [deployed frontera cms pprd main (at older commit `e5756c7`)](https://github.com/TACC/Core-Portal-Deployments/commit/b20a07c) to show [FP-1423](https://github.com/TACC/Core-CMS/pull/444), a change that has since been merged to `main`.

</details>

2022-02-28 22:45 UTC, edmondsgarrett commented
> @edmondsgarrett, [Frontera pprd](https://pprd.frontera-portal.tacc.utexas.edu/) now has correct code deployed:
> 
> * this branch
> * at commit up-to-date with `main`
> 
> What Happened?

I am still seeing the same thing (border extends to the ends of the window) on pprd Frontera.

2022-03-01 01:45 UTC, tacc-wbomar commented
Try [clearing cache](https://kinsta.com/knowledgebase/how-to-clear-browser-cache/#single), Compadre. 🙂

2022-03-01 16:21 UTC, edmondsgarrett approved these changes
LGTM! All changes described were confirmed.

2022-03-01 16:32 UTC, edmondsgarrett requested changes
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/43251554/156209104-b804c19b-47a7-4076-8c05-714995abd2b3.png">

These two borders should be the same length (via @tacc-wbomar).

2022-03-02 17:24 UTC, tacc-wbomar commented
@edmondsgarrett I think I got it now.

New border solution is added via f3b7919, then via 6e185f1, new solution is limited to just `.container.o-section`[^1].

<details>

1. **Problem**: New _real_ border is full width on `.o-section`. Padding of a `.container.o-section`[^1] makes border longer.
2. **Solution**: Shorten the border for `.container.o-section`[^1]'s.
3. **Problem**: No way to "shorten" a _real_ border.
4. **Solution**: Create a tool to draw a fake "short border". use new tool _only_ on a `.container.o-section`[^1].

</details>

[^1]: An `.o-section` class on a Bootstrap container. Created by editors via Container plugin. Used on Frontera homepage but __not__ on Section Pattern page.

2022-03-02 18:36 UTC, edmondsgarrett approved these changes
LGTM!

2022-03-02 20:33 UTC, merged