Use ManifestStaticFilesStorage for cache busting
TACC/Core-CMS pull request #648
Opened 2023-05-25 22:23 UTC by jarosenb

## Overview
By setting `ManifestStaticFilesStorage` as the backend, our static files will have hashed filenames. This will prevent stale content from being served to users when we update our styles. It will also prevent `collectstatic` from doing a no-op instead of overwriting files.

2023-05-25 22:32 UTC, wesleyboar commented on taccsite_cms/settings.py
> +STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
This seems to [become deprecated in Django 4.2](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STORAGES), which we want to use soon. If so, would you recommend we note that somewhere ([Jira](https://jira.tacc.utexas.edu/browse/TUP-454)) (code comment here)? _The new way (not available until 4.2) would be [via `STORAGES` setting](https://docs.djangoproject.com/en/4.2/ref/settings/#std-setting-STORAGES)._

2023-05-25 22:38 UTC, taoteg commented
As long as we don't hit this bug: https://github.com/django-cms/djangocms-text-ckeditor/issues/474

2023-05-25 22:44 UTC, wesleyboar commented
@taoteg, we ought not to. You [brought us up to `djangocms-text-ckeditor` v3.10](https://github.com/TACC/Core-CMS/commit/6396956#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R59) and @jarosenb [brought us up to v5](https://github.com/TACC/Core-CMS/commit/9ff0f1e#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R59). If that exists, that app needs help. I'll test.

2023-05-25 23:03 UTC, wesleyboar commented
Well, crap. It got through the CSS of `ckeditor` at least, but it died on one of Django's SVGs.

`ValueError: The file 'cms/fonts/src/logo.svg' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0xffffb1ced6d0>.`

<details>

```
root@core_cms:/code# python manage.py collectstatic
Found another file with the destination path 'admin/img/search.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'djangocms_text_ckeditor/ckeditor/contents.css'. It will be ignored since only the […]
Found another file with the destination path 'utrc-cms/img/org_logos/utrc-horizontal-logo-white-simple.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Post-processing 'cms/css/3.7.4/cms.welcome.css' failed!

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
    raise processed
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 294, in _post_process
    content = pattern.sub(converter, content)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 193, in converter
    hashed_url = self._url(
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 343, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 93, in hashed_name
    raise ValueError("The file '%s' could not be found with %r." % (filename, self))
ValueError: The file 'cms/fonts/src/logo.svg' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0xffffb1ced6d0>.
```

</details>

2023-05-25 23:03 UTC, wesleyboar requested changes
Well, crap. It got through the CSS of `ckeditor` at least, but it died on one of Django's SVGs. I dunno what to do yet. This week has taken much of my brain already.

`ValueError: The file 'cms/fonts/src/logo.svg' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0xffffb1ced6d0>.`

<details>

```
root@core_cms:/code# python manage.py collectstatic
Found another file with the destination path 'admin/img/search.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Found another file with the destination path 'djangocms_text_ckeditor/ckeditor/contents.css'. It will be ignored since only the […]
Found another file with the destination path 'utrc-cms/img/org_logos/utrc-horizontal-logo-white-simple.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
Post-processing 'cms/css/3.7.4/cms.welcome.css' failed!

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 188, in handle
    collected = self.collect()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 134, in collect
    raise processed
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 294, in _post_process
    content = pattern.sub(converter, content)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 193, in converter
    hashed_url = self._url(
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 132, in _url
    hashed_name = hashed_name_func(*args)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 343, in _stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/django/contrib/staticfiles/storage.py", line 93, in hashed_name
    raise ValueError("The file '%s' could not be found with %r." % (filename, self))
ValueError: The file 'cms/fonts/src/logo.svg' could not be found with <django.contrib.staticfiles.storage.ManifestStaticFilesStorage object at 0xffffb1ced6d0>.
```

</details>

2023-05-26 17:49 UTC, taoteg commented
After making the setting changes in the host, did you rerun collect static to validate the manifest? `python manage.py collectstatic --clear --noinput`

2023-05-26 18:22 UTC, wesleyboar commented
@taoteg, I used this branch, and confirmed setting on my host was synced to container. I ran that command with `--clear --no-input` and received the same output.

2023-11-13 21:54 UTC, wesleyboar commented
I am still interested in this. I retain the branch and keep the PR open.

"By setting ManifestStaticFilesStorage as the backend [...] prevent stale content […]"
This is a familiar and good feature. I have used it in my pre-TACC CMS work.

"It will also prevent collectstatic from doing a no-op instead of overwriting files."
This would clean up log cruft too.

2024-03-07 12:01 UTC, daandeheij commented
Are you guys still having issues with this? I am not sure if you are encountering the same issue as mentioned [here](https://github.com/django-ckeditor/django-ckeditor/issues/675). I just left a [solution](https://github.com/django-ckeditor/django-ckeditor/issues/675#issuecomment-1983349227) there, because somehow I couldn't find it anywhere online. Anyways, if you're having difficulties, I can probably help out if you want.

2024-03-07 18:30 UTC, wesleyboar commented
**Hi, @daandeheij. Thank you for the reference!**

<details><summary>I suspect our issue was <strong>not</strong> with CKEditor.</summary>

Because the log showed `Post-processing 'cms/css/3.7.4/cms.welcome.css' failed!` before the error — and that's a Django CMS v3.7.4 stylesheet, unrelated to CKEditor.

</details>

I am still unsure of the reason, for this _initial_ attempt at `ManifestStaticFilesStorage`. When I have the bandwidth and requirement, I'll merge `main` and test again — maybe with newer syntax — because this repo has had major dependency upgrades and other relevant changes since.

---

**P.R. Status Update**

@jarosenb tried `ManifestStaticFilesStorage` this year also. It [failed in Core-CMS](https://github.com/TACC/Core-CMS/pull/780/commits/d2c6f01), but [worked in a client app](https://github.com/TACC/tup-ui/pull/400). This project, an upstream CSS lib, and other clients, needed several changes to support [that new solution](https://github.com/TACC/tup-ui/pull/400).

- https://github.com/TACC/Core-CMS/pull/780
- https://github.com/TACC/Core-Styles/pull/285
- https://github.com/TACC/Core-CMS-Resources/pull/197

2025-02-03 18:08 UTC, wesleyboar commented on taccsite_cms/settings.py
> +STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
We use Django 4.2 now (e20c1c9, #707, [v4.0.0](https://github.com/TACC/Core-CMS/tree/v4.0.0)), so `STATICFILES_STORAGE` is deprecated.

2025-02-03 18:10 UTC, wesleyboar commented
> [!NOTE]
> **Status:**
> - The [current solution is deprecated](https://github.com/TACC/Core-CMS/pull/648#discussion_r1939817330).
> - This [feature is still a good idea](https://github.com/TACC/Core-CMS/pull/648#issuecomment-1809189952).

2026-07-21 23:31 UTC, wesleyboar commented
Closed, and documented as issue #1212 instead.

2026-07-21 23:31 UTC, closed without merging