Task/TUP-702 Make new windows accessible
TACC/Core-CMS pull request #803
Opened 2024-02-20 00:03 UTC by R-Tomas-Gonzalez

## Overview

Creates accessibility for external links

## Related

- [TUP-702](https://tacc-main.atlassian.net/browse/TUP-702)

## Changes

- New windows are not inherently accessible
- We dynamically set the attribute of `target="_blank"`, so let's add `aria-description='Opens in new window.'` and `rel=noopener`

## Testing

1. Add an external link
2. Make sure link has `aria-description` attribute and `rel=noopener`

## UI

<img width="2548" alt="Screenshot 2024-02-19 at 4 37 23 PM" src="https://github.com/TACC/Core-CMS/assets/63771558/edf63bc0-067a-4c9b-8cda-28d86bd996c3">

2024-02-20 00:32 UTC, wesleyboar requested changes
Please,

1. <details><summary>Un-commit migration files.</summary>

    _You may delete the migrations from your local server._

    </details>
2. <details><summary>Undo unrelated formatting changes, so diff is clear.</summary>

    _Let's figure out what code editor settings are causing this. Maybe your code editor is (appropriately) using the [Core-CMS `.editorconfig`](https://github.com/TACC/Core-CMS/blob/v4.8.1/.editorconfig), and I need to format the whole repo to match or something._

    </details>

2024-02-21 03:15 UTC, R-Tomas-Gonzalez commented
> Please,
> 
> 1. Un-commit migration files.
>    _You may delete the migrations from your local server._
> 2. Undo unrelated formatting changes, so diff is clear.
>    _Let's figure out what code editor settings are causing this. Maybe your code editor is (appropriately) using the [Core-CMS `.editorconfig`](https://github.com/TACC/Core-CMS/blob/v4.8.1/.editorconfig), and I need to format the whole repo to match or something._

Fixed

2024-02-21 19:58 UTC, wesleyboar commented on taccsite_cms/static/site_cms/js/modules/setTargetForExternalLinks.js
> + export default function findLinksAndSetTargets(options) {
```suggestion
export default function findLinksAndSetTargets(options) {
```

2024-02-22 00:40 UTC, wesleyboar approved these changes

2024-02-22 00:40 UTC, merged